In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
Y = np.array([[1], [0], [0], [1]])
np.random.seed(1)

# Weights as Random
weightForFirstLayer = np.random.random((3, 4)) 
weightForSecondLayer = np.random.random((4, 1))

print(weightForFirstLayer)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]]


In [3]:
# Activation Functions (Sigmoid)
def activationFunction(x):
    return (1/(1+np.exp(-x)))

In [4]:
# Derivative Function
def derivative(x):
    return x * (1 - x)

In [5]:
for i in range(60000):
    # Layers
    layer1 = activationFunction(np.dot(X, weightForFirstLayer))
    layer2 = activationFunction(np.dot(layer1, weightForSecondLayer))
    
    # Error
    layer2Error = Y - layer2
    
    if (i % 10000) == 0:
        print('Error ' + str( np.mean(layer2Error)) ) 
    
    layer2Derivative = derivative(layer2)
    layer2Delta = layer2Error * layer2Derivative
    
    layer1Error= np.dot(layer2Delta, weightForSecondLayer.T)
    layer1Derivative = derivative(layer1)
    layer1Delta = layer1Error * layer1Derivative
    
    weightForSecondLayer = weightForSecondLayer + np.dot(layer1.T, layer2Delta)
    weightForFirstLayer = weightForFirstLayer + np.dot(X.T, layer1Delta)

Error -0.28018321782132505
Error -0.0010933187187912759
Error -0.0007838736494232583
Error -0.0006474026683720904
Error -0.0005657620847940052
Error -0.0005097897856850384


In [6]:
np.round(layer2, 3)

array([[0.998],
       [0.005],
       [0.004],
       [0.994]])